name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  ci-fuzz-api-token: # id of input
    description: 'CI Fuzz Access Token'
    required: true
  github-token: # id of input
    description: 'Github Access Token'
    required: true
  repo: # id of input
    description: 'repository to run Fuzz test'
    required: true
  name: # id of input
    description: 'name of the check'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'dist/index.js'
